language: node_js
node_js:
  - "4.2"
before_install:
  - make install
script:
  - make test
notifications:
notifications:
  email:
    recipients:
      - ezpaarse-team@googlegroups.com
      - dominique.lechaudel@gmail.com
    on_success: change
    on_failure: always
  slack: 'inist-dpi:53Jp5iUZeRidSGZn0TukMSKo#activity'
