language: node_js
node_js:
  - "4.2"
install: true
notifications:
  slack:
    secure: p/7J6LXqmmkQBaJ4q3KUibZgzKevo+ExTOiY+O4UQQa597dbK72gMWp+RKYVnfrhoMfTPD8oS8JG9nu74s6/mKHAtVc/g0qPH549tHpFC1DqD7G0TNUZxNV1tiWXkNbSPe59tkrn9R95azIA52cDXA1i9cguOYnCLysmEPUMQwU=
